targets:
  $default:
    builders:
      bloc_gen_runner:
        options:
          equatable: true
          transformer: "debounce(milliseconds: 700)"
          is_builder: false
          is_listener: true