name: bloc_gen_annotations
description: "Type-safe BLoC annotations for states and events, simplifying bloc_concurrency and equatable with 6 sealed transformers."
version: 0.0.1+4
# Published on GitHub: https://github.com/makri-aymen/bloc_gen_runner
repository: https://github.com/makri-aymen/bloc_gen_runner
issue_tracker: https://github.com/makri-aymen/bloc_gen_runner/issues
homepage:

topics:
  - bloc
  - bloc-concurrency
  - state-management
  - code-generator
  - annotations

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^9.2.0
  bloc_concurrency: ^0.3.0
  equatable: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:

screenshots:
  - description: The bloc_gen_annotations package logo.
    path: screenshots/logo.png